### ISSUE TITLE
Build guide

### ISSUE THREAD

**Issue by penguinwithpants** [Librum-Reader/Librum-Server#1]
A guide to build and run the server would be very helpful, I've tried running `src/Presentation` in Visual Studio and it throws an error:

`Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'no such table: AspNetUsers'.'` 

I don't know what to try beyond that as I've never worked with SQLite or ASP.NET.

**Comment by zlian1758** [comment]
Adding a Dockerfile would be great.

**Comment by Creapermann** [comment]
We'll add a Dockerfile soon, thanks for the feedback.

**Comment by DavidLazarescu** [comment]
I have added a build guide in the last commit e74b1a294a7860049d2e77995ba02772bbcc2a61
