### ISSUE TITLE
Configuring a Windows client with selfhosted server

### ISSUE THREAD

**Issue by tenekev** [Librum-Reader/Librum-Server#12]
I decided to test your newly created docker image but hit a wall on the last step. The selfhosted instructions say that the config file is located in `~/.config/Librum-Reader/Librum.conf` but that's Linux-agnostic.

On my Win11 installation, I can't find such a file. Not in my profile folder, or the Appdata folder or the installation directory.

**Comment by DavidLazarescu** [comment]
Hey, for windows, please try and look for such file in the following locations
![image](https://github.com/Librum-Reader/Librum-Server/assets/69865187/29fe06a5-b504-4164-9133-8e8f75ff9deb)

Where APPNAME is Librum-Reader

**Comment by tenekev** [comment]
Wow, such a fast reply.

`C:\Users\User\AppData\Local\Librum-Reader\Librum` contains only a cache folder for `qmlcache` and `qtpipelinecache`.
`C:\ProgramData` does not contain any Librum-related stuff.

My Librum version is the latest 0.10.1 so that can't be the issue.

**Comment by DavidLazarescu** [comment]
Ok, I have booted into my windows machine to test this. It seems like Qt does not create a file for the settings like on liunx, but it uses the Windows Registry.

You will need to do the following to edit it:
    1. Open Registry Editor:
        Press Win + R to open the Run dialog.
        Type regedit and press Enter.

    2. Navigate to the Key:
        In Registry Editor, navigate to HKEY_CURRENT_USER\Software\Librum-Reader\Librum. You can do this by expanding the folders in the left pane.

    3. Edit Values:
        Once you've located the key, you can edit the values in the right pane. Right-click on the value you want to modify and choose Modify.
        Enter the new data in the "Value data" field.

    Close Registry Editor:
        After making changes, close the Registry Editor.

This way you should be able to change it to what you need.
