### ISSUE TITLE
"Requested access to the resource is denied" when installing in OpenMediaVault

### ISSUE THREAD

**Issue by zeitchef** [Librum-Reader/Librum-Server#21]
I'm trying to install in OMV6 using the built-in docker compose plugin. I'm getting an error I've never encountered before and wanted to confirm this was not an issue on your side. The error states that I don't have pull access for Librum and suggests either the repository doesn't exist or that I need to login.

<img width="520" alt="Screenshot 2023-12-19 at 23 47 56" src="https://github.com/Librum-Reader/Librum-Server/assets/6670659/620422e7-19fa-4af8-906d-b944ebadde48">

I've logged into Docker (though I've never needed to do this before) and I still get the error. I would appreciate any suggestion on how I can resolve this, or take it up with OMV if this is an error coming from their side. Thanks a bunch!

**Comment by IXEguy** [comment]
Just wanted to confirm, you have built the image locally per the instructions?

Running the docker-compose file will only work after that as the project does not currently publish an image online, so there is nowhere to pull from.

(I haven't gotten the project working yet either, but I was able to successfully build an image locally and bring it up after adapting the docker-compose to use my existing mariadb server)

**Comment by zeitchef** [comment]
Ah, I did overlook the part about building locally, thanks for that. I’ll give it another go. Closing this for now.

**Comment by zeitchef** [comment]
I'm reopening this as now there seems to be an issue with starting the container. Build seems to run fine, but there is no `labrum` container created or started. Manually attempting to start the container reports an error.

<img width="1578" alt="Screenshot 2023-12-20 at 09 15 04" src="https://github.com/Librum-Reader/Librum-Server/assets/6670659/442e0904-1411-4399-a7b5-6644e66eb891">

**Comment by tenekev** [comment]
You created an image tagged `docker.io/library/librum`. The default image tag in the compose is called just `librum` and it creates a container using this particular image tag. Did you update it after building the image with the new tag?

Maybe try `docker image tag docker.io/library/librum librum` and see what happens.

**Comment by zeitchef** [comment]
Oh, I forgot to come back to this - yes, I got it running. Closing.
