### ISSUE TITLE
How to configure for the client application on Windows

### ISSUE THREAD

**Issue by qwasdev** [Librum-Reader/Librum-Server#28]
I have configured it and restart app according to the [doc](https://github.com/Librum-Reader/Librum-Server/blob/main/self-hosting/self-host-installation.md#configuration-for-the-client-application), but the self-hosting doesn't seem to work, I still need to input my account registered on librumreader.com

app version:  0.11.0

![image](https://github.com/Librum-Reader/Librum-Server/assets/134053124/540963ef-11a4-4216-a5f3-44446aa87f20)

**Comment by DavidLazarescu** [comment]
Configuring the windows client doesnt work by this approach. I have added a description for windows in the dev/develop branch of Librum which will be merged into main on the next release. You can find it [here](https://github.com/Librum-Reader/Librum/tree/dev/develop#self-hosting) for now.
