### ISSUE TITLE
API documentation and alternative clients

### ISSUE THREAD

**Issue by giacomocerquone** [Librum-Reader/Librum-Server#30]
Hey there. Thank you for this work, looks great and I like it a lot.
I was wondering, are the APIs documented somewhere already? I'd also like to know if alternative clients from third parties are something you're considering having or not.

**Comment by DavidLazarescu** [comment]
Hey, sorry for the late reply. The API is not documented as it was not meant to be used by different clients (but definitely can be).

We are focusing on our own clients but since the project is licensed under the AGPL license everyone can use it.

**Comment by giacomocerquone** [comment]
> Hey, sorry for the late reply. The API is not documented as it was not meant to be used by different clients (but definitely can be).
> 
> We are focusing on our own clients but since the project is licensed under the AGPL license everyone can use it.

Thank you for the info!
